#spring.profiles=docker
## tomcat \u7AEF\u53E3
server.version=0.0.5
server.port=28081

app.name=spirit
spring.application.name=spirit

#db.url=jdbc:sqlite:d:\\flower\\db\\app.db

server.servlet.session.timeout=PT24H
#
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

spring.servlet.multipart.max-file-size = 100MB

spring.servlet.multipart.max-request-size = 150MB

spring.jpa.show-sql=false
spring.jpa.generate-ddl=true  
spring.jpa.hibernate.ddl-auto=update

# thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML 
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html 
spring.thymeleaf.cache=false


logging.config=classpath:logback.xml
logging.file.path=/app/log/
logging.file.name=app.log


spring.mvc.static-path-pattern=/static/**

## docker \u90E8\u7F72\u90E8\u5206  docker  \u9700\u8981\u5C06 
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlite:/app/db/spirit.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



file.save.path:/app/resources
file.app.path:/app/
file.save.staticAccessPath:/cos/**
file.save:/cos


# Quartz \u914D\u7F6E
spring.quartz.job-store-type=memory
spring.quartz.properties.org.quartz.threadPool.threadCount=2
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.scheduler.instanceName=CollectDataScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
